"""
config.py — all runtime settings for the job-search bot.

Two-layer config:
  1. profile.json  — persona settings derived from your resume by bootstrap.py
                     (search terms, keywords, location, email).
                     Run `python bootstrap.py` to (re-)generate this file.
  2. This file     — infrastructure settings (API keys, thresholds, intervals,
                     job boards) that require manual decisions.

Hardcoded fallbacks here are used only when profile.json is absent.
"""

import json
import os

# ---------------------------------------------------------------------------
# Load profile.json (generated by bootstrap.py)
# ---------------------------------------------------------------------------

_PROFILE_PATH = "profile.json"
_profile: dict = {}

if os.path.exists(_PROFILE_PATH):
    with open(_PROFILE_PATH) as _f:
        _profile = json.load(_f)
    print(f"[config] Loaded profile from {_PROFILE_PATH} "
          f"({_profile.get('seniority', '?')} | {_profile.get('location', '?')})")
else:
    print(f"[config] WARNING: {_PROFILE_PATH} not found. "
          f"Run `python bootstrap.py` to generate it from your resume. "
          f"Using built-in fallbacks for now.")


def _p(key, fallback):
    """Return profile value if present and non-empty, else fallback."""
    val = _profile.get(key)
    if val is None or val == "" or val == [] or val == {}:
        return fallback
    return val


# ---------------------------------------------------------------------------
# Persona settings (driven by profile.json, fallback to sensible defaults)
# ---------------------------------------------------------------------------

# Search queries sent to JSearch (Google for Jobs aggregator).
# Each query = 1 API request per run. Keep short — see JSEARCH_INTERVAL_HOURS.
JSEARCH_QUERIES: list[str] = _p("search_terms", [
    "Technical Lead Ruby on Rails India",
    "Ruby on Rails Lead Engineer remote India",
])[:2]  # cap at 2 to respect free-tier budget (200 req/month)

# Search queries sent to Apify multi-board scraper.
APIFY_SEARCH_TERMS: list[str] = _p("search_terms", [
    "Technical Lead Ruby on Rails",
    "Ruby on Rails Backend Lead India",
    "Staff Engineer Ruby on Rails remote",
    "Backend Architect Rails AWS",
])

# Keyword filter — job title/description must contain at least one (case-insensitive).
KEYWORDS: list[str] = _p("keywords", [
    "ruby on rails", "rails",
    "technical lead", "backend lead", "engineering lead",
    "staff engineer", "principal engineer", "backend architect",
    "engineering manager",
])

# Primary target country. Jobs in this country are always included.
TARGET_COUNTRY: str = _p("country", "India")

# Candidate location string used in scoring prompts.
CANDIDATE_LOCATION: str = _p("location", "India")

# Candidate summary used in scoring prompts.
CANDIDATE_SUMMARY: str = _p("summary", "Experienced backend engineer targeting senior/lead roles.")

# Seniority level — used to penalise junior roles in scoring.
CANDIDATE_SENIORITY: str = _p("seniority", "lead")

# Email destination for digests (falls back to env var, then empty).
EMAIL_TO: str = _p("email", os.environ.get("EMAIL_TO", ""))

# ---------------------------------------------------------------------------
# API credentials (always from environment, never from profile)
# ---------------------------------------------------------------------------

JSEARCH_API_KEY  = os.environ.get("RAPIDAPI_KEY")
# JSearch is currently disabled — the API provider deprecated the /search endpoint.
# Set to True manually once a working replacement is configured.
JSEARCH_ENABLED: bool = False
APIFY_API_KEY    = os.environ.get("APIFY_API_KEY")
EMAIL_FROM       = os.environ.get("GMAIL_ADDRESS")
EMAIL_APP_PASSWORD = os.environ.get("GMAIL_APP_PASSWORD")
GEMINI_API_KEY   = os.environ.get("GEMINI_API_KEY")

# ---------------------------------------------------------------------------
# Infrastructure settings (manual decisions, not resume-derived)
# ---------------------------------------------------------------------------

# JSearch cadence (currently disabled — API deprecated by provider).
JSEARCH_INTERVAL_HOURS: int = 6

# Apify cadence. At $0.003/job, default ~$65/month.
# Raise to 12 or 24 to reduce spend.
APIFY_INTERVAL_HOURS: int = 6

# Job boards to scrape. naukri covers India; linkedin/indeed/glassdoor are global.
# Supported: linkedin, indeed, glassdoor, google, zip_recruiter, bayt, bdjobs, naukri
APIFY_JOB_BOARDS: list[str] = ["linkedin", "indeed", "glassdoor", "naukri"]

# Max results per board per search term (1–100). Directly controls Apify cost.
APIFY_MAX_RESULTS: int = 20

# Direct-to-company ATS polling (free, unlimited). Add company slugs:
#   https://boards.greenhouse.io/{slug}  → GREENHOUSE_COMPANIES
#   https://jobs.lever.co/{slug}         → LEVER_COMPANIES
GREENHOUSE_COMPANIES: list[str] = []
LEVER_COMPANIES: list[str] = []

# Only include jobs posted within this many days.
# Sensible values: 1 (24h), 7 (week), 30 (month), 90 (3 months)
POSTED_WITHIN_DAYS: int = 7

# Score threshold: jobs below this are stored but not emailed or given materials.
SCORE_THRESHOLD: int = 70

# Location/visa filter. When True:
#   - Remote jobs: must signal India-timezone acceptance.
#   - International on-site: must mention visa sponsorship.
FILTER_INTERNATIONAL: bool = True

VISA_SPONSORSHIP_PHRASES: list[str] = [
    "visa sponsorship", "sponsor visa", "work visa", "work permit",
    "sponsorship provided", "will sponsor", "relocation assistance",
]

INDIA_REMOTE_PHRASES: list[str] = [
    "india", "ist", "asia", "apac", "anywhere", "worldwide", "global",
    "all timezones", "any timezone", "flexible timezone", "overlap",
]

# Gemini model. gemini-2.0-flash has 1,500 req/day on free tier (vs 25 for 2.5-flash).
# Falls back to gemini-2.5-flash-lite if primary model quota is exhausted.
MODEL: str = "gemini-2.0-flash"
MODEL_FALLBACK: str = "gemini-2.5-flash-lite"

# File paths
DB_PATH: str = "jobs.db"
RESUME_PATH: str = "resume.txt"
