"""
config.py — all runtime settings for the job-search bot.

Two-layer config:
  1. profile.json  — persona settings derived from your resume by bootstrap.py
                     (search terms, keywords, location, email).
                     Run `python bootstrap.py` to (re-)generate this file.
  2. This file     — infrastructure settings (API keys, thresholds, intervals,
                     job boards) that require manual decisions.

Hardcoded fallbacks here are used only when profile.json is absent.
"""

import json
import os

# ---------------------------------------------------------------------------
# Load profile.json (generated by bootstrap.py)
# ---------------------------------------------------------------------------

_PROFILE_PATH = "profile.json"
_profile: dict = {}

if os.path.exists(_PROFILE_PATH):
    with open(_PROFILE_PATH) as _f:
        _profile = json.load(_f)
    print(f"[config] Loaded profile from {_PROFILE_PATH} "
          f"({_profile.get('seniority', '?')} | {_profile.get('location', '?')})")
else:
    print(f"[config] WARNING: {_PROFILE_PATH} not found. "
          f"Run `python bootstrap.py` to generate it from your resume. "
          f"Using built-in fallbacks for now.")


def _p(key, fallback):
    """Return profile value if present and non-empty, else fallback."""
    val = _profile.get(key)
    if val is None or val == "" or val == [] or val == {}:
        return fallback
    return val


# ---------------------------------------------------------------------------
# Persona settings (driven by profile.json, fallback to sensible defaults)
# ---------------------------------------------------------------------------

# Anchor skill — the candidate's single defining technology.
# Gets the highest skill bonus (+20 in title, +10 in description).
ANCHOR_SKILL: str = _p("anchor_skill", "React")

# Primary skills (excluding anchor) — get smaller bonuses (+5 each in title).
PRIMARY_SKILLS: list[str] = _p("primary_skills", [
    "JavaScript", "Frontend Architecture", "TypeScript", "Redux", "Micro Frontends",
])

# Search queries sent to JSearch (Google for Jobs aggregator).
# Each query = 1 API request per run. Keep short — see JSEARCH_INTERVAL_HOURS.
JSEARCH_QUERIES: list[str] = _p("search_terms", [
    "Senior Software Engineer Frontend India",
    "Senior Frontend Engineer India",
])[:2]  # cap at 2 to respect free-tier budget (200 req/month)

# Search queries sent to Apify multi-board scraper.
APIFY_SEARCH_TERMS: list[str] = _p("search_terms", [
    "Senior Software Engineer Frontend India",
    "Senior Frontend Engineer India",
    "Lead Frontend Engineer",
    "Lead UI Developer",
    "Senior Software Developer - Web",
    "Senior React Frontend Developer"
])

# Keyword filter — job title/description must contain at least one (case-insensitive).
KEYWORDS: list[str] = _p("keywords", [
    "react", "frontend", "html", "css", "micro frontend", "javascript", "typescript", "redux", 
    "senior software engineer", "frontend lead", "senior software lead",
    "ui developer", "frontend developer", "frontend architect", "web developer", 
    "react.js developer", "next.js", ""
])

# Primary target country. Jobs in this country are always included.
TARGET_COUNTRY: str = _p("country", "India")

# Candidate location string used in scoring prompts.
CANDIDATE_LOCATION: str = _p("location", "India")

# Candidate summary used in scoring prompts.
CANDIDATE_SUMMARY: str = _p("summary", "Experienced senior software frontend engineer targeting senior/lead roles.")

# Seniority level — used to penalise junior roles in scoring.
CANDIDATE_SENIORITY: str = _p("seniority", "senior/lead")

# Email destination for digests (falls back to env var, then empty).
EMAIL_TO: str = _p("email", os.environ.get("EMAIL_TO", "vinayjrao96@gmail.com"))

# ---------------------------------------------------------------------------
# API credentials (always from environment, never from profile)
# ---------------------------------------------------------------------------

JSEARCH_API_KEY  = os.environ.get("RAPIDAPI_KEY")
# JSearch is currently disabled — the API provider deprecated the /search endpoint.
# Set to True manually once a working replacement is configured.
JSEARCH_ENABLED: bool = False
APIFY_API_KEY    = os.environ.get("APIFY_API_KEY")
EMAIL_FROM       = os.environ.get("GMAIL_ADDRESS")
EMAIL_APP_PASSWORD = os.environ.get("GMAIL_APP_PASSWORD")
GEMINI_API_KEY   = os.environ.get("GEMINI_API_KEY")

# ---------------------------------------------------------------------------
# Infrastructure settings (manual decisions, not resume-derived)
# ---------------------------------------------------------------------------

# JSearch cadence (currently disabled — API deprecated by provider).
JSEARCH_INTERVAL_HOURS: int = 1

# Apify cadence. Set to 1 to run every hour.
# Cost at default settings: ~$0.54 per run × 24 runs/day ≈ $13/day or ~$390/month.
# Raise to 6 or 12 to reduce spend.
APIFY_INTERVAL_HOURS: int = 1

# Job boards to scrape. naukri covers India; linkedin/indeed/glassdoor are global.
# Supported: linkedin, indeed, glassdoor, google, zip_recruiter, bayt, bdjobs, naukri
APIFY_JOB_BOARDS: list[str] = ["linkedin", "indeed", "glassdoor", "naukri"]

# Max results per board per search term (1–100). Directly controls Apify cost.
APIFY_MAX_RESULTS: int = 20

# Direct-to-company ATS polling (free, unlimited). Add company slugs:
#   https://boards.greenhouse.io/{slug}  → GREENHOUSE_COMPANIES
#   https://jobs.lever.co/{slug}         → LEVER_COMPANIES
GREENHOUSE_COMPANIES: list[str] = []
LEVER_COMPANIES: list[str] = []

# Only include jobs posted within this many days.
# Sensible values: 1 (24h), 7 (week), 30 (month), 90 (3 months)
POSTED_WITHIN_DAYS: int = 30

# Score threshold: jobs below this are stored but not emailed or given materials.
SCORE_THRESHOLD: int = 60

# Location/visa filter. When True:
#   - Remote jobs: must signal India-timezone acceptance.
#   - International on-site: must mention visa sponsorship.
FILTER_INTERNATIONAL: bool = True

VISA_SPONSORSHIP_PHRASES: list[str] = [
    "visa sponsorship", "sponsor visa", "work visa", "work permit",
    "sponsorship provided", "will sponsor", "relocation assistance",
]

INDIA_REMOTE_PHRASES: list[str] = [
    "india", "ist", "asia", "apac", "anywhere", "worldwide", "global",
    "all timezones", "any timezone", "flexible timezone", "overlap",
]

# Gemini models — cascading fallback list. The bot tries each in order until one works.
# When a model returns 429 (quota exhausted), the next model is tried.
# Limits vary by project and change over time — check yours at:
# https://aistudio.google.com/app/plan_information
# All models below support generateContent for text scoring.
GEMINI_MODELS: list[str] = [
    "gemini-2.0-flash",              # Highest free-tier daily quota (~1,500/day)
    "gemini-2.0-flash-lite",         # Same tier, lightweight (~1,500/day)
    "gemini-2.5-flash-lite",         # Good free quota (~1,000/day)
    "gemini-2.5-flash",              # Smart, moderate quota (~250/day)
    "gemini-2.5-pro",                # Best quality, low quota (~100/day)
    "gemini-3.5-flash",              # Latest generation
    "gemini-3.1-flash-lite",         # Latest lightweight
    "gemini-3-flash-preview",        # Preview — may have limited quota
]

# File paths
DB_PATH: str = "jobs.db"
RESUME_PATH: str = "resume.txt"
